# docker build -f Dockerfile.x86_64 -t pgeraghty/ruby-microservice-run:x86_64-edge .
FROM multiarch/alpine:x86_64-edge

RUN apk update && apk upgrade \
    && apk add ca-certificates \
    libxml2 libxslt libevent libffi glib ncurses readline \
    openssl yaml zlib curl mariadb-libs libpq ruby ruby-io-console \
    && rm -rf /var/cache/apk/*